### ISSUE TITLE
Vote for release of `v0.2.0`

### ISSUE THREAD

**Issue by shizhMSFT** [oras-project/oras-dotnet#103]
At least 2 approvals are needed from the 3 maintainers for tagging c2c560c552b650d311710090ab888ddb51ab0590 as `v0.2.0`.

- [x] Samson Amaugo (@sammychinedu2ky)
- [x] Shiwei Zhang (@shizhMSFT)
- [x] Sylvia Lei (@Wwwsylvia)

The changes compared to `v0.1.0` include:

- #20
- #21
- #23
- #28
- #29
- #30
- #31
- #32
- #33
- #67
- #68
- #69
- #70
- #71
- #34
- #75
- #76
- #77
- #78
- #79
- #85
- #84
- #86
- #88
- #87
- #89
- #90
- #92
- #93
- #95
- #94
- #97
- #96
- #98
- #99
- #100
- #101
- #102
- #104
- #105 

See [the full changelog](https://github.com/oras-project/oras-dotnet/compare/v0.1.0...c2c560c552b650d311710090ab888ddb51ab0590) for more details.
Please respond LGTM or REJECT (with reasoning).

**Comment by shizhMSFT** [comment]
LGTM

**Comment by Wwwsylvia** [comment]
LGTM

**Comment by FeynmanZhou** [comment]
LGTM but I am not a maintainer of this repository. 

Thanks @shizhMSFT refactored the oras-dotnet SDK, formalized the contribution and release workflow, and added a few docs after v0.1.0, which makes the project easier for people to contribute.

**Comment by sammychinedu2ky** [comment]
Lots of changes and improvements !!! Awesome

**Comment by shizhMSFT** [comment]
Closed as [v0.2.0](https://github.com/oras-project/oras-dotnet/releases/tag/v0.2.0) was released.
