### ISSUE TITLE
Azure ACR ResolveAsync missing required header (InvalidResponse)

### ISSUE THREAD

**Issue by leonardochaia** [oras-project/oras-dotnet#143]
### What happened in your code base?

Hi, I am trying to do a copy between ACR and local `registry:2` container.

> Unhandled exception: System.Net.Http.HttpIOException: HEAD https://redacted.azurecr.io/v2/my-ns/some-ui/manifests/v2.3.2: missing required header  (InvalidResponse)
   at OrasProject.Oras.Registry.Remote.HttpResponseMessageExtensions.GenerateDescriptorAsync(HttpResponseMessage response, Reference reference, CancellationToken cancellationToken)
   at OrasProject.Oras.Registry.Remote.ManifestStore.ResolveAsync(String reference, CancellationToken cancellationToken)
   at OrasProject.Oras.Registry.Remote.Repository.ResolveAsync(String reference, CancellationToken cancellationToken)
   at OrasProject.Oras.Extensions.CopyAsync(ITarget src, String srcRef, ITarget dst, String dstRef, CancellationToken cancellationToken)

trying to curl the failing request uri does return the expected Docker-Content-Digest header.

Tried debugging and apparently, the `response.Contents.Headers` does not have the header: 
![image](https://github.com/user-attachments/assets/55a7ccdf-6082-47d5-abee-486f250e83ec)
but `response.Headers` does have it :
![image](https://github.com/user-attachments/assets/fefe0f9c-d90a-4824-b9c1-dfea5a5bc79f)

### What did you expect to happen?

I expected the reference to be resolved instead of an exception being thrown.

### How can we reproduce it?

When `ResolveAsync` is executed it throws the exception.

```csharp
var sourceRegistryClient = new HttpClientWithBasicAuth(...);
var image = "my-registry.azurecr.io/ns/image:v2.3.2"
 var sourceRepository = new Repository(
                    image,
                    sourceRegistryClient);
await sourceRepository.ResolveAsync(image, cancellationToken);

```

### What is the version or commit of the ORAS .NET library?

0.2.0 from nuget

### What are your OS and Runtime environments?

Fedora 40 and .NET 8.0

### Are you willing to submit PRs to fix it?

- [X] Yes, I am willing to fix it.

**Comment by leonardochaia** [comment]
This appears to be fixed on main branch. I've just cloned the repo, built from source code and tried the same test and it passed.

Is there a chance we can bump the nuget.org version of this package?

**Comment by Wwwsylvia** [comment]
Hi @leonardochaia , good catch!

> Is there a chance we can bump the nuget.org version of this package?

Yeah we can release a patch version `v0.2.1` on the main branch.

**Comment by leonardochaia** [comment]
Hi @Wwwsylvia , thank you that would be very appreciated :+1:

**Comment by Wwwsylvia** [comment]
Hi @leonardochaia , `[v0.2.1`](https://www.nuget.org/packages/OrasProject.Oras/0.2.1) is now available on NuGet! 🙂

**Comment by leonardochaia** [comment]
Thanks @Wwwsylvia , I think we can close this one :1st_place_medal:
