### ISSUE TITLE
Support cross-repository mounting of blobs

### ISSUE THREAD

**Issue by Wwwsylvia** [oras-project/oras-dotnet#153]
Similar to [oras-go](https://pkg.go.dev/oras.land/oras-go/v2/registry@v2.5.0#Mounter), we should support [cross-repository mounting of blobs](https://github.com/opencontainers/distribution-spec/blob/v1.1.0/spec.md#mounting-a-blob-from-another-repository) to enhance the performance.

**Comment by shizhMSFT** [comment]
Closed by #152
