### ISSUE TITLE
Consider enabling CA2007 rule to require `ConfigureAwait(false)` on all awaited tasks

### ISSUE THREAD

**Issue by leonardochaia** [oras-project/oras-dotnet#168]
### What would you like to be added?

I would like the .editorconfig to be modified to include the CA2007 rule, which requires awaited tasks to have `ConfigureAwait(false)`

https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca2007

### Why is this needed for the ORAS .NET library?

This would make reviewing PRs easier since we, as a library, must `ConfigureAwait(false)` everywhere.

Sample PR implementing such changes:
https://github.com/dotnet/aspnetcore/pull/39946

Confirm we want it and I'll create the PR :+1: 

### Are you willing to submit PRs to contribute to this feature?

- [X] Yes, I am willing to implement it.

**Comment by shizhMSFT** [comment]
This is a good idea. Let's have a try.
