### ISSUE TITLE
Provide .NET SDK for ORAS

### ISSUE THREAD

**Issue by FeynmanZhou** [oras-project/oras-dotnet#6]
### What is the version of your ORAS CLI

v0.16.0

### What would you like to be added?

ORAS has Python and Golang SDK that allow developers to build their own clients on top of one of the libraries. Similarly, developing a .NET SDK will enable .Net developers to use ORAS API and enhance the ORAS ecosystem.

This issue is open for the [CNCF LFX Mentorship 2023 program](https://github.com/cncf/mentoring/tree/main/lfx-mentorship/2023/01-Mar-May). If you are interested in implementing this issue, please let us know.

### Why is this needed for ORAS?

 Enable .Net developers to use ORAS API and enhance the ORAS ecosystem.

### Are you willing to submit PRs to contribute to this feature?

- [ ] Yes, I am willing to implement it.

**Comment by shizhMSFT** [comment]
Closing this issue as the LFX program has ended.
